### ISSUE TITLE
what is the exact exposure pattern for TESS?

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/HoneyComb#25]
Hey @zkbt : I am simulating a TESS lightcurve.

TESS takes data in 2-second exposures.  What is the exact number I should replace "2.0000" with?  Also, what is the dead time (if any) between the 2-second exposures?

I pay beer for answers.

**Comment by zkbt** [comment]
The time between adjacent sub-exposures will be 2.000000 seconds. According
to Ed Morgan on the TESS team, the exposure time is defined as two pulses
of 1 pulse-per second spacecraft clock. This clock isn't guaranteed to be
exact and isn't synchronized with GPS, so a separate onboard "High Accuracy
Clock" will be used to track any long-term drift between its exposure
timestamps and real time systems. These drifts should be small compared to
the barycenter correction, but are worth mentioning.

The CCD's are being read out as frame transfer arrays. The time to transfer
pixels into the frame store will be something like 5 milliseconds. (This
number will depend on the final properties of the flight detector and
electronics, but this is the latest I've heard.) During this 5
milliseconds, the light from every star will be smeared out over its entire
column, and this smear will be subtracted off in calibration. Unless
something really crazy happens to a very bright star during that 5
milliseconds, this effectively means the cadence will be 1.995 seconds of
exposure followed by 0.005 seconds of dead time.

Hope this helps! Will send a response on the Hogg 2.0 cosmic ray filter
when I get the chance. It's pushing the memory limits, so will have to be
really good to make it on board.

Cheers,
Z

————_————_————

Zachory K. Berta-Thompson
Torres Exoplanet Fellow
MIT Kavli Institute
77 Massachusetts Ave., 37-673
Cambridge, MA 02139
phone: 617-253-5084
web: space.mit.edu/~zkbt

——————————__——

**Comment by zkbt** [comment]
Oops -- a factor of 10 correction to what I just said. The frame transfer
time could be as large as 50 milliseconds (but will hopefully be
significantly lower). In that worst case scenario, the exposure time would
be 1.95 seconds and the dead time would be 0.05 seconds.

————_————_————

Zachory K. Berta-Thompson
Torres Exoplanet Fellow
MIT Kavli Institute
77 Massachusetts Ave., 37-673
Cambridge, MA 02139
phone: 617-253-5084
web: space.mit.edu/~zkbt

——————————__——

**Comment by zkbt** [comment]
(Realizing you probably prefer the predicted rather than worst case...):

Word just came from Roland Vanderspeck that it looks like current best
estimate is 20 milliseconds of frame transfer time.

————_————_————

Zachory K. Berta-Thompson
Torres Exoplanet Fellow
MIT Kavli Institute
77 Massachusetts Ave., 37-673
Cambridge, MA 02139
phone: 617-253-5084
web: space.mit.edu/~zkbt

——————————__——

**Comment by davidwhogg** [comment]
Thank you very  much @zkbt !  This is exactly what I wanted.

**Comment by davidwhogg** [comment]
I am closing this for now; I am doing things as realistically as I ever intend to (for now).
